% Code example for RBE3001 MATLAB crash course - Fall 2017
%
%
% This file reads “history.csv” file, which is generated by “simulate.m”, 
% and displays the corresponding joint angle histories.
%
% Author: Siamak G. Faal
%         sghorbanifaal@wpi.edu
%         http://users.wpi.edu/~sghorbanifaal/index.html
% Date: August 24, 2017


% Clear "Command Window", clear all the variables in "Workspace" and close
% all the figures.
clc; clear; close all;

% Read the path history of the robot from "history.csv" file
q = csvread('history.csv');

% Plot q1 history
plot(q(:,1)); 

% Hold on to the objects in the figure axes
hold on;

% Plot q2 history
plot(q(:,2)); 

% Set the plot legends and axes' names
legend('q_1','q_2');
xlabel('time steps');
ylabel('q');